server:
  port: 9090
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/vue
    username: root
    password: root
#    url: jdbc:h2:
  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: com.vue_spring.common.hibernate.naming.CustomPhysicalStrategy
      use-new-id-generator-mappings: true
    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: false
#      path: /h2-console

logging:
  level:
    root: warn
#    org.hibernate: debug
