server:
  port: 9090
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:vue
    username: vue
    password: vue
  devtools:
    livereload:
      enabled: true


  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  output:
    ansi:
      enabled: always


logging:
  level:
    root: INFO
    org.hibernate: debug
